"""Here we collect all the endpoints that we will use"""

pinned_videos = "https://open.tiktokapis.com/v2/research/user/pinned_videos/"
"""Pinned videos endpoint"""
comments = "https://open.tiktokapis.com/v2/research/video/comment/list/"
"""Comment endpoint"""
followers = "https://open.tiktokapis.com/v2/research/user/followers/"
"""Followers endpoint"""
followings = "https://open.tiktokapis.com/v2/research/user/following/"
"""Followings endpoint"""
user_info = "https://open.tiktokapis.com/v2/research/user/info/"
"""User info endpoint"""
liked_videos = "https://open.tiktokapis.com/v2/research/user/liked_videos/"
"""Liked videos endpoint"""
query = "https://open.tiktokapis.com/v2/research/video/query/"
"""Search query endpoint"""
oauth = "https://open.tiktokapis.com/v2/oauth/token/"
"""OAuth token endpoint"""
